---
title: "An Ecologist’s Introduction to Transitioning into Data Science"
---


## Instructors

- [Alessandro Filazzola](http://www.filazzola.info) 
- [Sophie Breitbart](https://sbreitbart.github.io/)

<!-- ESA/CSEE link -->
<!-- <a class="btn btn-info" href="https://easyretro.io/publicboard/gEdRrWVYh9ZQztnmdn94aX87HO83/43aac0ef-9bd6-4721-a8ae-5b31b1063993"> Offer Feedback </a> &larr; It's quick & simple, we promise! -->

<!-- SORTEE link -->
<a class="btn btn-info" href="https://easyretro.io/publicboard/gEdRrWVYh9ZQztnmdn94aX87HO83/0c348100-c4bb-47fe-aa1b-921280201759"> Offer Feedback </a> &larr; It's quick & simple, we promise!

## General Information

**Ecological researchers have skills that are highly transferable.** For instance, ecologists are frequently tasked with

-Understanding how to deal with the noisy and complex data

-Ecologists are also skillful in data management, complex analytics, and diverse methods to extract actionable insights and answer scientific research questions.

**All of these skills are also essential for data science.**

For individuals looking for a career outside of academia, data science can satisfy an interest in answering complex, interesting research objectives such as understanding consumer insights, detecting fraud, ensuring cyber security, or designing video games. There are also opportunities for potential gains in work-life balance and compensation. However, *translating an ecologist's experiences into relevant skills for a data science position requires some understanding of both disciplines.*

**In this workshop, we use our experiences as data science-curious ecologists (who are presently in or have recently left academia) to discuss important considerations for those contemplating a career shift from academic ecology to industrial data science.** We will discuss ways in which programming languages and key tools are shared between disciplines as well as skills that are relatively industry-specific. This workshop will also include **interactive activities** such as a short introduction to SQL and a **Q&A** with former ecologists who are now in data science.

This workshop will involve a combination of lecture and hands-on activities. A basic understanding of R is recommended because it will make the content more relevant and understandable, but even novices can listen and learn about the general concepts behind functions. Participants should use a computer with R already install using Mac, Linux, or Windows operating system (not a tablet, Chromebook, etc.).

**Who**: The course is aimed at academic ecologists and evolutionary biologists who are curious about non-tenure track careers that incorporate aspects of data science in their everyday roles.

<!-- **When**: Tuesday, August 16 \@ 11:45am-1:15pm EDT -->

<!-- **Where**: Room 513D -->

**When**: Wednesday, November 2 \@ 10am-12pm EDT

**Where**: Virtually. [Sign up here](https://www.eventbrite.com/e/an-ecologists-introduction-to-transitioning-into-data-science-tickets-444256161137)

**Requirements**: Participants should use a laptop with a Mac, Linux, or Windows operating system (not a tablet, Chromebook, etc.) with administrative privileges. However, participation is not necessary and you can simply follow along as we demonstrate.

**Contact**: Please contact [sophie.breitbart\@mail.utoronto.ca](mailto:sophie.breitbart@mail.utoronto.ca) for more information.


## Software

[R](http://www.r-project.org/) is a programming language that is especially powerful for data exploration, visualization, and statistical analysis. To interact with R, we use [RStudio](http://www.rstudio.com/).

| Windows                                                                                                                                                                                                                                              | Mac OS X                                                                                                                                                                                                                                        | Linux                                                                                                                                                                                         |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Install R by downloading and running [this .exe](http://cran.r-project.org/bin/windows/base/release.htm) file from [CRAN](http://cran.r-project.org/index.html). Please also install the [RStudio IDE](http://www.rstudio.com/ide/download/desktop). | Install R by downloading and running [this .pkg](http://cran.r-project.org/bin/macosx/R-latest.pkg) file from [CRAN](http://cran.r-project.org/index.html). Please also install the [RStudio IDE](http://www.rstudio.com/ide/download/desktop). | You can download the binary files for your distribution from [CRAN](http://cran.r-project.org/index.html). Please also install the [RStudio IDE](http://www.rstudio.com/ide/download/desktop) |

**Packages we will be using:** We recommend you install these ahead of time and ensure they load correctly to reduce troubleshooting in the workshop.

`install.packages(c("dplyr", "dbplyr", "RSQLite", "magrittr"))`

## Diversity Statement

Improving the accessibility and retention of enjoyable, well-paying jobs for underrepresented and historically excluded communities has continuously been a core theme in support of EDI. Unfortunately, many ecologists from nearly all educational levels struggle to obtain permanent, full-time positions at a salary that is suitable to their qualifications. As a result, the typical job instability and low wages that ecologists must endure are substantial barriers to the goal of improving inclusivity of diverse individuals in ecology because of the potential financial hardship for those without privileged socio-economic standing. Data science has emerged as a potential alternative career for ecologists intent on continuing their roles as skilled researchers but who might prioritize factors like job stability, salary accordant with experience, and work/life balance, which are notoriously difficult to obtain in academic ecology. Data science is also an intrinsically interdisciplinary field which necessitates the confluence of diverse perspectives and sources of knowledge— a tenet which underlies ESA's Diversity Statement.

We are striving to create a positive, inclusive environment that encourages our participants to see new potential career opportunities in data science. We aim to empower our participants and help them navigate the job market by introducing them to resources that are instrumental for transitioning into this field. In this way, we are taking steps towards introducing our participants to opportunities they may not be aware of but can offer significant economic and personal advantages. We will administer this workshop with the understanding that there is structural inequity in both academic ecology and data science; indeed, despite the numerous benefits of the latter, the field possesses a distinct lack of diversity in technical and leadership roles. Specifically, individuals identifying as people of color and women are significantly underrepresented in technical roles and even more so in leadership roles.

Our list of organizers and contributors represents individuals from a range of career stages including graduate students, post-docs, and corporate careers. We also have individuals from underrepresented communities in ecology, evolution, and data science. All the workshop presenters are committed to improving EDI and increasing job accessibility for anyone interested in becoming a data scientist.

## Interviews with biologists --> data scientists

- [Highlight video](https://youtu.be/T1ET1NDiE3Y) shown at workshop
- Full-length interview with [Monica Granados](https://youtu.be/J-EKUK2gvnI)
- Full-length interview with [Jude Kong](https://youtu.be/ahD-MnFq9iA)
- Full-length interview with [Thomas Van Zuiden](https://youtu.be/pWz4zCGwZnM)

## Ecology/data science job boards

After our workshop, several participants asked us where to look for jobs suited for ecologists with data science skills. To our knowledge, there is no go-to resource for these types of positions. Instead, here are some sites that would be worth browsing regularly:

- [Academic Data Science Alliance](https://academicdatascience.org/jobs)
- [Zip Recruiter](https://www.ziprecruiter.com/Jobs/Ecology-Data-Science)
- [Women in Machine Learning & Data Science](http://wimlds.org/jobs/)
- [R-users](https://www.r-users.com/)
- [Indeed](https://www.indeed.com/jobs?q=Data+Science+ecology&l=&vjk=3b4800de970c28e7)
- [Texas A&M Natural Resources Job Board](https://wfscjobs.tamu.edu/?s=%22data+scien%22&post_type=job_posting)

## Other workshops

If you enjoyed this workshop and were interested in learning more, we have also run workshops on

-   [How to improve the reproducibility and efficiency of your coding for ecology and evolution (FastR)](https://github.com/afilazzola/FastR)
-   [Writing R functions](https://sbreitbart.github.io/BGSS_Retreat_2021_Workshop/)

Additionally, Alex has run these workshops:

-   [Logistic Regression](https://github.com/afilazzola/CUELogisticRegression)
-   [Introduction to Ecological Analyses](https://afilazzola.github.io/UoA.CommunityAnalyses.2018/)
-   [Introduction to Functions](https://afilazzola.github.io/Intro2Functions/)

You can find similar style workshops, usually that are longer and go into more detail, with [The Carpentries](https://carpentries.org/workshops-curricula/). They have teachers available globally and cover all forms of programming beyond R.

<br>

## Thank You!

